name: Islah.AI
description: Namaz Posture Correction App
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  camera: ^0.10.5+2
  path: ^1.8.3
  path_provider: ^2.0.15
  lottie: ^2.6.0
  flutter_local_notifications: ^8.1.1+1
  adhan: ^2.0.0
  timezone: ^0.7.0
  geolocator: ^7.0.3
  location: ^5.0.3
  sensors_plus: ^4.0.2
  vector_math: ^2.1.4
  google_fonts: ^4.0.4
  video_player: ^2.8.3
  http: ^1.2.1
  http_parser: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/